{ config, lib, ... }:
let
  terraformWorkingDir = "/home/gideon/infra/home/vms/";
in
{
  # Generate the terraform variables file
  # The rest of the terraform configuration gets generated by terranix
  sops.templates."terranix-proxmox-creds.json".content = builtins.toJSON {
    proxmox_api_token_id = ${config.sops.placeholder."proxmox/api_token_id"};
    proxmox_api_token_secret = ${config.sops.placeholder."proxmox/api_token_secret"};
  };


  # Stick the secret file where Terraform can use it
  systemd.services.terraform-proxmox-seed-secrets = {
    description = "Seed Terraform tfvars";
    wantedBy = [ "multi-user.target" ];
    serviceConfig.Type = "oneshot";
    script = ''
      set -e
      mkdir -p ${terraformWorkingDir}
      if [ ! -f ${terraformWorkingDir}/terraform.tfvars.json ]; then
        install -m 600 ${
          config.sops.templates."terranix-proxmox-creds.json".path
        } ${terraformWorkingDir}/secrets.yml
      fi
      if [ ! -f ${terraformWorkingDir}/terraform.tfvars.json ]; then
        install -m 600 ${config.sops.templates."terranix-proxmox-creds.json".path} ${terraformWorkingDir}/terraform.tfvars.json
      fi
      chown -R 1000:100 ${terraformWorkingDir}
      chmod 755 ${terraformWorkingDir}
    '';

}