{config, ... }:
# This file is responsible for staging the secrets that terraform needs to authenticate with various platforms. 
# The secrets get generated by sops-nix 
let
    # This is the root directory where all my terraform infrastructure will be contained
    terraformWorkingDir = "/home/gideon/infra/";
    # Specific directories that will be used for different terraform modules
    terraformProxmoxDir = "${terraformWorkingDir}/home/proxmox";
    terraformNetboxDir = "${terraformWorkingDir}/netbox";
in
{
    # Define the secrets that Terraform needs to authenticate with proxmox
    sops.secrets."proxmox/api_token_id" = {
        sopsFile = ./secrets_terraform.yaml;
    };
    sops.secrets."proxmox/api_token_secret" = {
        sopsFile = ./secrets_terraform.yaml;
    };
    # Put these secrets in a SOPS template file
    sops.templates."terranix-proxmox-creds.json" = {
        # Template of the file
        content = builtins.toJSON {
            proxmox_api_token_id = config.sops.placeholder."proxmox/api_token_id";
            proxmox_api_token_secret = config.sops.placeholder."proxmox/api_token_secret";
            proxmox_api_url = "http://${config.custom.world.hosts.proxmox.nodes.pve1.ip}:8006/api2/json";
        };
        # Where to put the generated file
        path = "${terraformProxmoxDir}/terraform.tfvars.json";
        # Make sure I own it
        owner = "gideon";
    };

    # Define the secrets that Terraform needs to authenticate with netbox
    sops.secrets."netbox/api_token" = {
        sopsFile = ./secrets_terraform.yaml;
    };
    # Put these secrets in a SOPS template file
    sops.templates."terranix-netbox-creds.json" = {
        # Template of the file
        content = builtins.toJSON {
            netbox_api_token = config.sops.placeholder."netbox/api_token";
            netbox_server_url = "http://${builtins.toString config.custom.world.services.netbox.ip}:${builtins.toString config.custom.world.services.netbox.port}";
        };
        # Where to put the generated file
        path = "${terraformNetboxDir}/terraform.tfvars.json";
        # Make sure I own it
        owner = "gideon";
    };

}