keys:
  - &users:
      - &gideon CFDDC2FC81DEE54D1C4BFF58538305FABF463DE5
  - &hosts:
      - &poseidon age10exe2vqxqapa87r7xxyrzessgk9efjac05s3znsl66xzfm6pqgpqp6793w
      - &media-vm age1pq948k582rh0u5xwtdwl4v4ml8ny9tf3h8ns7l28hcu9ja5nz40stq98ux
creation_rules:
  - path_regex: gideon_secrets.yaml$
    key_groups:
      - age:
          - *poseidon
        pgp:
          - *gideon
  - path_regex: secrets_media.yaml$
    key_groups:
      - age:
          - *media-vm
        pgp:
          - *gideon