traefik:
    env: ENC[AES256_GCM,data:XoWnkyTonNOTuYsSzzqB6wsBd2msZEbOKv2nMPUzidKWwwxHxhaD6ALuGOl3p9z9zk+4NbY1nW6ZBGN4o0k9DgjZoD3MIlTYKtClKGJ7pYT0wzO9sls=,iv:HXTPYq8lKGTZ3JPyzKjOw4wmrCeKkOqGxwOOdrxkpPA=,tag:pulHfL17tUqNxxzFIN3ilA==,type:str]
crowdsec:
    api_key: ENC[AES256_GCM,data:d7pwSSC5nJL1+q+gc1Rs5bxpdHjPvr9w5/Ff4ULrZrGvZSdwAIfoUuwK2Q==,iv:K8EWou7TM4OXF9BWm6ohmz4iZWJmBDOc40Cp9WRGiwo=,tag:tT7JmQDsyy7JelxQZejbhg==,type:str]
sops:
    age:
        - recipient: age1d5pt3hh8ssv5qk77t204undqg3n9lt5y0vavhutuf9fqnewsjq9qs573rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHV0Y4N1VTZFFGTXlJM0Vq
            WXhwcmQ3dk1QOS9BUDRleXdCZDZ0SGliQlF3Cis0NFd5ZGdHVURKdHorSVNLU2dB
            S0pBZkNQaHpJd2c0Y1oyb09PNCsrNWsKLS0tIGZMdXl1K1Y1Q3U3Q2RjYnBXRnVv
            d3RTdlpib09xTWlOdTUxU1RSNE90b00KTebHe66dmJUr/hl7EPtoTm6HDcTyybgd
            uFhzSwuSF/3yJ9fQrW4QeSdV1yrkLQdwPkSEs+3S1cmM5YqWCTq4fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T18:13:36Z"
    mac: ENC[AES256_GCM,data:Qo/iq4s/ry7mXgypTChjJoPPy95K6Dirbv6wHogiis/cRHZDuMC88su5PVL7HCPrvHbCvFghhEr0I10erpXVSzdn/UR0Bk9WOvy6qVEFYKrKcZzfP6YP6P0m9MjvOaAc1AxRMYINRaUsz+xKYQ3tguNPUghMcUq99FuJiqPBgMg=,iv:F33t8EBEpmD6FB0TM0iD/JXaZYtfXtI4LQ079e/9pnw=,tag:sarhbDZosrTOAT+eWTxIXw==,type:str]
    pgp:
        - created_at: "2026-05-19T17:06:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DW7pTteVLMFESAQdAIj8Wuj72r9iru1TrY1ZjdD0I6btf/gUvxhW6HuruLV8w
            BH1ml1yx4bB752zuiM6RGcT9ZqLhWPP9WJAfBOI66OEcMAl0+pbUTw3rNzKKREHz
            0l4B411MLIHog4lIktIM2JyN2hYevs65u+2+Zp8elmyXlCj/nG9EV/Jm37WrtnaY
            4s7Hwk26/6cVLBsLJ6E5EWbktb44YIo489ekkzor23zyfU0A2Qw5Uvl34UtgNsfE
            =hlZj
            -----END PGP MESSAGE-----
          fp: CFDDC2FC81DEE54D1C4BFF58538305FABF463DE5
    unencrypted_suffix: _unencrypted
    version: 3.11.0
