traefik:
    env: ENC[AES256_GCM,data:XoWnkyTonNOTuYsSzzqB6wsBd2msZEbOKv2nMPUzidKWwwxHxhaD6ALuGOl3p9z9zk+4NbY1nW6ZBGN4o0k9DgjZoD3MIlTYKtClKGJ7pYT0wzO9sls=,iv:HXTPYq8lKGTZ3JPyzKjOw4wmrCeKkOqGxwOOdrxkpPA=,tag:pulHfL17tUqNxxzFIN3ilA==,type:str]
crowdsec:
    api_key: ENC[AES256_GCM,data:A4t3XbpFitVNPIVi3BP7fo8W0++CJ5O6C1AKkNLPvZmoSI3IjoM+U6OpyQ==,iv:ICODXiuR/DTDMssjSml/KX61LM+LeRZj4ZIBRTHhnmo=,tag:DfvMxB5qyNq+Y3Db3JBcVA==,type:str]
sops:
    age:
        - recipient: age1zuwvpzy4ajrc9r8tv4956j3ml3ytncmap0tujk2d8nyypyjlpcws629ysp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSldtOEZhYUpMTE84enVy
            b2Zmc0JwU3ZYY2lnZ1c0SStxSGpTZkt1OUdnCjlYYWtvbEhBN3lVWm0xdDdXN2xN
            THhpN3lzYm1RTVcwbS93cUNBWGlaVzQKLS0tIGdPOG1OZStzQ2xBOUdtOXd2dXJv
            MjJOcWN1VldpT1M3VmVuc1JoYUh4c2cKKi7XzjzXnOWmrx1OtTDHIEysCtwrosON
            Wffmv25Z4zm9g55eK6l10YLQx5Ky+J9TS59Uyihe7ar/wdnwIeULDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T20:05:19Z"
    mac: ENC[AES256_GCM,data:Yp2gwwv3rcEoDhL+7JPOXeuyAbIGyJbDok/z3ESBHeaX+eEFrI+X1QsvWbYjz5e733qZHT9hszsa3WfBbGqJsFeU24l5TJw3NGRR0ziTl3MIQRXYT5NgUQKh2dDwDO/iw8Bcuak2MfQ5hUng/80gqsIfEEcdFzvKhcBLVr7V/jk=,iv:pPUltGusz93+9C/krFcGkP1am6fTyPKSuWevLmmO3S0=,tag:2HJOxJMv8BTNvrmQAjOGOw==,type:str]
    pgp:
        - created_at: "2026-05-23T18:30:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DW7pTteVLMFESAQdAKXNKJqGybnYwkkx17dU+KlAw0zcQKidN3Cg5UH/LoC8w
            YGQmr6HOtKNszTRrpEINVox+g8NebsT6ITHADE9BgjX7sqjym4iwAqZu/998V0H7
            0l4Bes3uzWkPKsabbZZo/o0ieMocVRJZgB8tjBxCCCcoRNe0TU9Xg8VQwduoNKqZ
            3PHqYVPbvUGMFxyiBFBw5uv/wprgoyR5xZ+8RlJfWsc9u7gldZuSvUvpLsE0M6P3
            =pW8N
            -----END PGP MESSAGE-----
          fp: CFDDC2FC81DEE54D1C4BFF58538305FABF463DE5
    unencrypted_suffix: _unencrypted
    version: 3.12.1
