mikrotik:
    rb5009:
        username: ENC[AES256_GCM,data:aMyoUdA=,iv:KiYOoqI5UDKj1O0xb2uuQhbF4gSWHlhkiwT9eZRwHC4=,tag:TL/QJW1rGJOf1Fyiq2monQ==,type:str]
        password: ENC[AES256_GCM,data:9tAxTgM9nSn1A6uEXXg=,iv:KsPXkqSC25+mSmr53j4lonNpRlzg+v2cHXy0UmHX6nE=,tag:4ivfYxWYcsAP4e7bxWE6Ew==,type:str]
    hapax2:
        username: ENC[AES256_GCM,data:Kf6QzO0=,iv:0/1fEpUjeFU31ueUgA5kUqQJtmmOORVbrIQsCZtT6Nc=,tag:uXLrId1sB6h+d4SpawFH+g==,type:str]
        password: ENC[AES256_GCM,data:E+Ipj+jyEcvUOsrzUUE=,iv:abR84yPLannUMAjfOzeQfkanT00VhWKpoC3Sp/LlbaA=,tag:fGP03CfBKCVJ02eji6uiEA==,type:str]
sops:
    age:
        - recipient: age1rmd30ancclvmupptkxwzrys2stfwxxdn6enuqm2us0l936hctyksljfqk7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeFRkT0lkOEFiV1FxVXQy
            Ri9raVVqeTY3WmNVU0daN0x2Zkh3eGxweEdVCmlOazhMOXB6VldYYVQzME5sN1ls
            dC9aRXQ0em9HV3BUQS83Q3hybERMRVkKLS0tIGlsMktnNEdUWGVDZ2VXU2hFSGJT
            ZmoxQlkzMVZZYzNETVNKR0VjUVNPeU0KSfsSrAJzlXkL8ti4l+iAhm0zF6I16XcB
            iT+2SxGZlXO5QrzfzP32WAd2LsXAorSIUhnlLpsJKfWIg8L7zHRerA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T04:16:42Z"
    mac: ENC[AES256_GCM,data:VSE3nfGN4WKdrNJAnGHs7umhB4A4vXZHdqLXkXThyBIScNSM2qlTgnMq8dbB+CvdI/6FFP1Vx3Ri3u3DrOubbyrac6NVFXRW3l+9TgXUGPCgu74uCigBquO+yKx1Lczraaaw1oDs9YRcYJiA6TKZ3Bb68IKFtA+bJOesX+ARw7U=,iv:+MaruDnngGsUSPC2E+XIyShCyOk+UlulO0Vp8OqPxpA=,tag:MpswxrMKJ0QR3i6qZR1UCw==,type:str]
    pgp:
        - created_at: "2026-07-31T04:12:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DW7pTteVLMFESAQdA74YAvgx4YLoa6126Jrjw9Y4X0+E8rIC0SUUtUAjTKUow
            atok7yyPNnjkio+4iWXZVaM4aKoh/rxxSKKQZP48i9GVdh+Kkj+qjufwmpwRuYVj
            0lwBuKcau4KhvQ5qgVCfL38Zv+dFPuFw258lXPUon6aW/XXCltMfXhDPF9kqR5HF
            ROrDpXJfvFbgixCe2O9/CYZNdlbyPttkqUoSIUePrjy92Z3FgfsGaly59D+Jrg==
            =shB5
            -----END PGP MESSAGE-----
          fp: CFDDC2FC81DEE54D1C4BFF58538305FABF463DE5
    unencrypted_suffix: _unencrypted
    version: 3.12.1
